---
# tasks file for ansible-role-local-users

- name: Add local user accounts
  user:
    name: "{{ item.0.username }}"
    shell: /bin/bash
    groups: "{{ item.0.groups | default(omit) }}"
    append: yes
  with_subelements: 
    - "{{ users }}"

- name: Add SSH public keys
  authorized_key:
    user: "{{ item.0.username }}"
    key: "https://github.com/{{ github_username }}"
  with_subelements:
    - "{{ users }}"
